In [1]:
import numpy as np

In [7]:
a = np.random.randint(1, 10, (2, 4))
b = np.random.randint(1, 10, (2, 4))

In [8]:
a

array([[5, 9, 2, 1],
       [6, 1, 5, 3]])

In [9]:
b

array([[4, 7, 3, 8],
       [3, 9, 5, 4]])

In [10]:
a+b

array([[ 9, 16,  5,  9],
       [ 9, 10, 10,  7]])

In [ ]:
# Rules for the addition and operation:--


# Rule1:-- Here it will check from the right and go towards the left if the numbers in the array are calculated 
# to be equal 

# Rule2:-- If one of the number in the array in the operation provided is 1 then also the operation will work in it

In [15]:
c = np.random.randint(1, 10, (2, 1))
d = np.random.randint(1, 10, (2, 4))

In [16]:
c

array([[6],
       [1]])

In [17]:
d

array([[1, 1, 4, 2],
       [5, 8, 8, 2]])

In [18]:
c+d

array([[ 7,  7, 10,  8],
       [ 6,  9,  9,  3]])

In [19]:
e = np.random.randint(1, 10, (40, 50, 2, 1))
f = np.random.randint(1, 10, (2, 4))

In [ ]:
# Here since 1 is present in the coed hence the code will work and 

In [21]:
e+f

array([[[[11, 10, 12,  8],
         [ 6,  9,  6,  4]],

        [[10,  9, 11,  7],
         [13, 16, 13, 11]],

        [[12, 11, 13,  9],
         [12, 15, 12, 10]],

        ...,

        [[10,  9, 11,  7],
         [13, 16, 13, 11]],

        [[12, 11, 13,  9],
         [10, 13, 10,  8]],

        [[ 8,  7,  9,  5],
         [ 9, 12,  9,  7]]],


       [[[ 7,  6,  8,  4],
         [ 6,  9,  6,  4]],

        [[13, 12, 14, 10],
         [ 6,  9,  6,  4]],

        [[ 9,  8, 10,  6],
         [10, 13, 10,  8]],

        ...,

        [[10,  9, 11,  7],
         [10, 13, 10,  8]],

        [[ 7,  6,  8,  4],
         [11, 14, 11,  9]],

        [[13, 12, 14, 10],
         [ 8, 11,  8,  6]]],


       [[[ 9,  8, 10,  6],
         [10, 13, 10,  8]],

        [[14, 13, 15, 11],
         [ 9, 12,  9,  7]],

        [[14, 13, 15, 11],
         [ 9, 12,  9,  7]],

        ...,

        [[ 9,  8, 10,  6],
         [12, 15, 12, 10]],

        [[ 7,  6,  8,  4],
         [12, 15, 12, 10]],

  